name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: j22868706/taipeidaytrip_app:latest,j22868706/taipeidaytrip_app:${{ github.sha }}
          cache-from: type=registry,ref=j22868706/taipeidaytrip_app:latest
          cache-to: type=inline

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          key_format: base64
          host: ${{ secrets.HOST_DNS }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Check if container exists before stopping and removing it to avoid errors on first deployment
            sudo docker pull j22868706/taipeidaytrip_app:latest
            if [ "$(sudo docker ps -q -f name=app)" ]; then
              sudo docker stop app
              sudo docker rm app
            fi

            # Run container with more complete configuration
            sudo docker run -d \
              --name app \
              --restart unless-stopped \
              -p 80:80 \
              -p 3000:3000 \
              j22868706/taipeidaytrip_app:latest

            # Verify the container is running
            sudo docker ps | grep app
